services:
  - type: web
    name: portfolio
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings.render
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          name: portfolio
          type: web
          property: host
